version: "3.7"

services:
  ch03-numbers-api:
    image: kiamol/ch03-numbers-api:latest
    build:
      context: ./numbers
      dockerfile: ./numbers-api/Dockerfile

  ch03-numbers-web:
    image: kiamol/ch03-numbers-web:latest
    build:
      context: ./numbers
      dockerfile: ./numbers-web/Dockerfile      

  ch03-numbers-web-v2:
    image: kiamol/ch03-numbers-web:v2
    build:
      context: ./numbers
      dockerfile: ./numbers-web-v2/Dockerfile

  ch03-sleep:
    image: kiamol/ch03-sleep:latest
    build:
      context: ./sleep